In [1]:
import csv 
import pandas as pd

In [2]:
df4 = pd.read_csv('2021_data/202104-citibike-tripdata.csv')
df4.head()

/Users/rebeccamelo/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7099F9531C9DA16D,docked_bike,2021-04-28 17:27:24,2021-04-28 17:34:31,DeKalb Ave & Hudson Ave,4513.06,Douglass St & 4 Ave,4175.14,40.689888,-73.981013,40.679279,-73.981540,member
1,EDC6F1B1A69A7863,docked_bike,2021-04-27 17:28:02,2021-04-27 17:33:07,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member
2,431A76830E10408A,docked_bike,2021-04-28 18:05:19,2021-04-28 18:10:48,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member
3,C00248A0ADC009FA,docked_bike,2021-04-20 21:35:47,2021-04-20 21:56:31,Irving Ave & DeKalb Ave,4898.02,Division Ave & Hooper St,5045.05,40.702700,-73.920950,40.706842,-73.954435,casual
4,BE78810D746EE516,docked_bike,2021-04-30 00:34:54,2021-04-30 01:03:29,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual

In [3]:
df4.rename(columns = {'ride_id': 'Ride ID', 'rideable_type': 'Rideable Type', 'started_at': 'Started At','ended_at': 'Ended At','start_station_name':'Start Station Name',
                      'start_station_id':'Start Station Id', 'end_station_name': 'End Station Name', 'end_station,id': 'End Station Id','start_lat':'Start Latitude',
                      'start_lng':'Start Longitude','end_lat':'End Latitude','end_lng':'End Longitude',
                      'member_casual':'Member Casual'}, inplace = True)
df4.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual
0,7099F9531C9DA16D,docked_bike,2021-04-28 17:27:24,2021-04-28 17:34:31,DeKalb Ave & Hudson Ave,4513.06,Douglass St & 4 Ave,4175.14,40.689888,-73.981013,40.679279,-73.981540,member
1,EDC6F1B1A69A7863,docked_bike,2021-04-27 17:28:02,2021-04-27 17:33:07,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member
2,431A76830E10408A,docked_bike,2021-04-28 18:05:19,2021-04-28 18:10:48,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member
3,C00248A0ADC009FA,docked_bike,2021-04-20 21:35:47,2021-04-20 21:56:31,Irving Ave & DeKalb Ave,4898.02,Division Ave & Hooper St,5045.05,40.702700,-73.920950,40.706842,-73.954435,casual
4,BE78810D746EE516,docked_bike,2021-04-30 00:34:54,2021-04-30 01:03:29,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual

In [4]:
df5 = pd.read_csv('2021_data/202105-citibike-tripdata.csv')
df5.head()

/Users/rebeccamelo/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E12103A91226099A,docked_bike,2021-05-06 17:25:01,2021-05-06 17:45:25,Broadway & W 60 St,6948.11,1 Ave & E 78 St,7020.09,40.769155,-73.981918,40.771404,-73.953517,member
1,26A3DC47FE0EA3A3,docked_bike,2021-05-13 12:48:08,2021-05-13 13:07:37,Broadway & W 25 St,6173.08,E 2 St & Avenue B,5515.02,40.742868,-73.989186,40.722174,-73.983688,member
2,A99F2E1D627B088F,docked_bike,2021-05-16 08:30:13,2021-05-16 08:45:47,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member
3,43E79A45997B7390,docked_bike,2021-05-01 08:38:14,2021-05-01 08:54:27,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member
4,8B3CC649F4F58816,docked_bike,2021-05-09 08:12:31,2021-05-09 08:27:05,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member

In [5]:
df5.rename(columns = {'ride_id': 'Ride ID', 'rideable_type': 'Rideable Type', 'started_at': 'Started At','ended_at': 'Ended At','start_station_name':'Start Station Name',
                      'start_station_id':'Start Station Id', 'end_station_name': 'End Station Name', 'end_station,id': 'End Station Id','start_lat':'Start Latitude',
                      'start_lng':'Start Longitude','end_lat':'End Latitude','end_lng':'End Longitude',
                      'member_casual':'Member Casual'}, inplace = True)
df5.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual
0,E12103A91226099A,docked_bike,2021-05-06 17:25:01,2021-05-06 17:45:25,Broadway & W 60 St,6948.11,1 Ave & E 78 St,7020.09,40.769155,-73.981918,40.771404,-73.953517,member
1,26A3DC47FE0EA3A3,docked_bike,2021-05-13 12:48:08,2021-05-13 13:07:37,Broadway & W 25 St,6173.08,E 2 St & Avenue B,5515.02,40.742868,-73.989186,40.722174,-73.983688,member
2,A99F2E1D627B088F,docked_bike,2021-05-16 08:30:13,2021-05-16 08:45:47,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member
3,43E79A45997B7390,docked_bike,2021-05-01 08:38:14,2021-05-01 08:54:27,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member
4,8B3CC649F4F58816,docked_bike,2021-05-09 08:12:31,2021-05-09 08:27:05,46 Ave & 5 St,6286.02,34th Ave & Vernon Blvd,6873.01,40.747310,-73.954510,40.765354,-73.939863,member

In [6]:
df6 = pd.read_csv('2021_data/202106-citibike-tripdata.csv')
df6.head()

/Users/rebeccamelo/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,6339C86D47EC0FAB,docked_bike,2021-06-02 17:18:45,2021-06-02 17:26:17,W 51 St & 6 Ave,6740.10,E 66 St & Madison Ave,6969.08,40.760659,-73.980420,40.768009,-73.968453,member
1,CDE3C147775B4002,docked_bike,2021-06-04 21:01:46,2021-06-04 21:32:09,W 56 St & 10 Ave,6955.01,E 9 St & Avenue C,5616.01,40.768254,-73.988639,40.725213,-73.977688,member
2,D335C3F6B412B846,docked_bike,2021-06-15 16:39:36,2021-06-15 16:55:02,E 56 St & Madison Ave,6732.01,E 16 St & 5 Ave,6022.04,40.761573,-73.972628,40.737262,-73.992390,member
3,8DA6810777C89735,docked_bike,2021-06-08 11:36:40,2021-06-08 11:39:41,E 68 St & 3 Ave,6896.16,1 Ave & E 62 St,6753.08,40.767128,-73.962246,40.761227,-73.960940,member
4,62D9B66A3A1D9FDF,docked_bike,2021-06-18 12:48:43,2021-06-18 13:04:14,E 48 St & 5 Ave,6626.01,W 20 St & 8 Ave,6224.05,40.757245,-73.978059,40.743453,-74.000040,member

In [7]:
df6.rename(columns = {'ride_id': 'Ride ID', 'rideable_type': 'Rideable Type', 'started_at': 'Started At','ended_at': 'Ended At','start_station_name':'Start Station Name',
                      'start_station_id':'Start Station Id', 'end_station_name': 'End Station Name', 'end_station,id': 'End Station Id','start_lat':'Start Latitude',
                      'start_lng':'Start Longitude','end_lat':'End Latitude','end_lng':'End Longitude',
                      'member_casual':'Member Casual'}, inplace = True)
df6.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual
0,6339C86D47EC0FAB,docked_bike,2021-06-02 17:18:45,2021-06-02 17:26:17,W 51 St & 6 Ave,6740.10,E 66 St & Madison Ave,6969.08,40.760659,-73.980420,40.768009,-73.968453,member
1,CDE3C147775B4002,docked_bike,2021-06-04 21:01:46,2021-06-04 21:32:09,W 56 St & 10 Ave,6955.01,E 9 St & Avenue C,5616.01,40.768254,-73.988639,40.725213,-73.977688,member
2,D335C3F6B412B846,docked_bike,2021-06-15 16:39:36,2021-06-15 16:55:02,E 56 St & Madison Ave,6732.01,E 16 St & 5 Ave,6022.04,40.761573,-73.972628,40.737262,-73.992390,member
3,8DA6810777C89735,docked_bike,2021-06-08 11:36:40,2021-06-08 11:39:41,E 68 St & 3 Ave,6896.16,1 Ave & E 62 St,6753.08,40.767128,-73.962246,40.761227,-73.960940,member
4,62D9B66A3A1D9FDF,docked_bike,2021-06-18 12:48:43,2021-06-18 13:04:14,E 48 St & 5 Ave,6626.01,W 20 St & 8 Ave,6224.05,40.757245,-73.978059,40.743453,-74.000040,member

In [8]:
df7 = pd.read_csv('2021_data/202107-citibike-tripdata.csv')
df7.head()

/Users/rebeccamelo/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,247BA541A9674BF3,classic_bike,2021-07-09 16:05:36,2021-07-09 16:18:09,5 Ave & E 93 St,7372.10,Frederick Douglass Blvd & W 117 St,7688.12,40.785785,-73.957481,40.805159,-73.954692,member
1,125C9ACA270A5E2D,classic_bike,2021-07-11 16:23:35,2021-07-11 16:29:07,5 Ave & E 93 St,7372.10,E 88 St & Park Ave,7293.10,40.785785,-73.957481,40.781411,-73.955959,member
2,2E26264BCC15BA05,classic_bike,2021-07-23 06:22:40,2021-07-23 06:36:13,34 St & 38 Ave,6453.02,McGuinness Blvd & Eagle St,5977.01,40.752443,-73.929737,40.735550,-73.952840,member
3,A56D23A088563424,classic_bike,2021-07-05 16:08:10,2021-07-05 16:36:00,Lenox Ave & W 111 St,7602.05,5 Ave & E 78 St,7161.08,40.798786,-73.952300,40.776321,-73.964274,casual
4,1451F4BB884C5335,classic_bike,2021-07-26 12:28:57,2021-07-26 12:30:21,6 Ave & Broome St,5610.09,6 Ave & Canal St,5500.07,40.724310,-74.004730,40.722438,-74.005664,casual

In [9]:
df7.rename(columns = {'ride_id': 'Ride ID', 'rideable_type': 'Rideable Type', 'started_at': 'Started At','ended_at': 'Ended At','start_station_name':'Start Station Name',
                      'start_station_id':'Start Station Id', 'end_station_name': 'End Station Name', 'end_station,id': 'End Station Id','start_lat':'Start Latitude',
                      'start_lng':'Start Longitude','end_lat':'End Latitude','end_lng':'End Longitude',
                      'member_casual':'Member Casual'}, inplace = True)
df7.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual
0,247BA541A9674BF3,classic_bike,2021-07-09 16:05:36,2021-07-09 16:18:09,5 Ave & E 93 St,7372.10,Frederick Douglass Blvd & W 117 St,7688.12,40.785785,-73.957481,40.805159,-73.954692,member
1,125C9ACA270A5E2D,classic_bike,2021-07-11 16:23:35,2021-07-11 16:29:07,5 Ave & E 93 St,7372.10,E 88 St & Park Ave,7293.10,40.785785,-73.957481,40.781411,-73.955959,member
2,2E26264BCC15BA05,classic_bike,2021-07-23 06:22:40,2021-07-23 06:36:13,34 St & 38 Ave,6453.02,McGuinness Blvd & Eagle St,5977.01,40.752443,-73.929737,40.735550,-73.952840,member
3,A56D23A088563424,classic_bike,2021-07-05 16:08:10,2021-07-05 16:36:00,Lenox Ave & W 111 St,7602.05,5 Ave & E 78 St,7161.08,40.798786,-73.952300,40.776321,-73.964274,casual
4,1451F4BB884C5335,classic_bike,2021-07-26 12:28:57,2021-07-26 12:30:21,6 Ave & Broome St,5610.09,6 Ave & Canal St,5500.07,40.724310,-74.004730,40.722438,-74.005664,casual

In [10]:
df8 = pd.read_csv('2021_data/202108-citibike-tripdata.csv')
df8.head()

/Users/rebeccamelo/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,FB6B89D05B67EBED,classic_bike,2021-08-24 15:59:57,2021-08-24 16:42:07,Broadway & E 21 St,6098.10,Central Park North & Adam Clayton Powell Blvd,7617.07,40.739888,-73.989586,40.799484,-73.955613,member
1,E13DA3E30CEF8DFC,classic_bike,2021-08-18 13:12:01,2021-08-18 13:21:26,E 13 St & 2 Ave,5820.08,Henry St & Grand St,5294.04,40.731539,-73.985302,40.714211,-73.981095,member
2,56617490AB8AE69C,classic_bike,2021-08-17 14:31:23,2021-08-17 14:35:34,E 95 St & 3 Ave,7365.13,E 84 St & Park Ave,7243.04,40.784903,-73.950503,40.778627,-73.957721,member
3,CA908B271C7D6663,classic_bike,2021-08-11 10:00:12,2021-08-11 10:31:01,Madison Ave & E 82 St,7188.13,E 84 St & Park Ave,7243.04,40.778131,-73.960694,40.778627,-73.957721,casual
4,3E170CE1F4FE179D,classic_bike,2021-08-12 19:28:38,2021-08-12 19:48:50,E 74 St & 1 Ave,6953.08,E 84 St & Park Ave,7243.04,40.768974,-73.954823,40.778627,-73.957721,casual

In [11]:
df8.rename(columns = {'ride_id': 'Ride ID', 'rideable_type': 'Rideable Type', 'started_at': 'Started At','ended_at': 'Ended At','start_station_name':'Start Station Name',
                      'start_station_id':'Start Station Id', 'end_station_name': 'End Station Name', 'end_station,id': 'End Station Id','start_lat':'Start Latitude',
                      'start_lng':'Start Longitude','end_lat':'End Latitude','end_lng':'End Longitude',
                      'member_casual':'Member Casual'}, inplace = True)
df8.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual
0,FB6B89D05B67EBED,classic_bike,2021-08-24 15:59:57,2021-08-24 16:42:07,Broadway & E 21 St,6098.10,Central Park North & Adam Clayton Powell Blvd,7617.07,40.739888,-73.989586,40.799484,-73.955613,member
1,E13DA3E30CEF8DFC,classic_bike,2021-08-18 13:12:01,2021-08-18 13:21:26,E 13 St & 2 Ave,5820.08,Henry St & Grand St,5294.04,40.731539,-73.985302,40.714211,-73.981095,member
2,56617490AB8AE69C,classic_bike,2021-08-17 14:31:23,2021-08-17 14:35:34,E 95 St & 3 Ave,7365.13,E 84 St & Park Ave,7243.04,40.784903,-73.950503,40.778627,-73.957721,member
3,CA908B271C7D6663,classic_bike,2021-08-11 10:00:12,2021-08-11 10:31:01,Madison Ave & E 82 St,7188.13,E 84 St & Park Ave,7243.04,40.778131,-73.960694,40.778627,-73.957721,casual
4,3E170CE1F4FE179D,classic_bike,2021-08-12 19:28:38,2021-08-12 19:48:50,E 74 St & 1 Ave,6953.08,E 84 St & Park Ave,7243.04,40.768974,-73.954823,40.778627,-73.957721,casual

In [12]:
df9 = pd.read_csv('2021_data/202109-citibike-tripdata.csv')
df9.head()

/Users/rebeccamelo/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,22C33F42C6A0E28E,classic_bike,2021-09-01 10:26:45,2021-09-01 10:43:23,Central Park West & W 72 St,7141.07,E 51 St & 1 Ave,6532.06,40.775794,-73.976206,40.754557,-73.965930,member
1,035F743147FCFCDE,classic_bike,2021-09-04 09:52:40,2021-09-04 10:09:19,William St & Pine St,5065.12,NaN,NaN,40.707179,-74.008873,40.720000,-74.010000,member
2,9C43CF6A07DACBC6,classic_bike,2021-09-06 17:07:40,2021-09-06 17:34:44,Fulton St & Broadway,5175.08,Jay St & Tech Pl,4710.06,40.711066,-74.009447,40.695065,-73.987167,casual
3,253A1A5B20CC78EE,classic_bike,2021-09-28 16:53:43,2021-09-28 17:03:00,West Drive & Prospect Park West,3651.04,Ocean Pkwy & Church Ave,3125.09,40.661063,-73.979453,40.644719,-73.974515,member
4,5E8F164D6798CEFA,classic_bike,2021-09-19 09:37:47,2021-09-19 09:53:42,Lorimer St & Broadway,4965.01,Jay St & Tech Pl,4710.06,40.704118,-73.948186,40.695065,-73.987167,member

In [13]:
df9.rename(columns = {'ride_id': 'Ride ID', 'rideable_type': 'Rideable Type', 'started_at': 'Started At','ended_at': 'Ended At','start_station_name':'Start Station Name',
                      'start_station_id':'Start Station Id', 'end_station_name': 'End Station Name', 'end_station,id': 'End Station Id','start_lat':'Start Latitude',
                      'start_lng':'Start Longitude','end_lat':'End Latitude','end_lng':'End Longitude',
                      'member_casual':'Member Casual'}, inplace = True)
df9.head()

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual
0,22C33F42C6A0E28E,classic_bike,2021-09-01 10:26:45,2021-09-01 10:43:23,Central Park West & W 72 St,7141.07,E 51 St & 1 Ave,6532.06,40.775794,-73.976206,40.754557,-73.965930,member
1,035F743147FCFCDE,classic_bike,2021-09-04 09:52:40,2021-09-04 10:09:19,William St & Pine St,5065.12,NaN,NaN,40.707179,-74.008873,40.720000,-74.010000,member
2,9C43CF6A07DACBC6,classic_bike,2021-09-06 17:07:40,2021-09-06 17:34:44,Fulton St & Broadway,5175.08,Jay St & Tech Pl,4710.06,40.711066,-74.009447,40.695065,-73.987167,casual
3,253A1A5B20CC78EE,classic_bike,2021-09-28 16:53:43,2021-09-28 17:03:00,West Drive & Prospect Park West,3651.04,Ocean Pkwy & Church Ave,3125.09,40.661063,-73.979453,40.644719,-73.974515,member
4,5E8F164D6798CEFA,classic_bike,2021-09-19 09:37:47,2021-09-19 09:53:42,Lorimer St & Broadway,4965.01,Jay St & Tech Pl,4710.06,40.704118,-73.948186,40.695065,-73.987167,member

In [14]:
citibike_2021 = pd.concat([df4, df5, df6, df7, df8, df9])
citibike_2021

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual
0,7099F9531C9DA16D,docked_bike,2021-04-28 17:27:24,2021-04-28 17:34:31,DeKalb Ave & Hudson Ave,4513.06,Douglass St & 4 Ave,4175.14,40.689888,-73.981013,40.679279,-73.981540,member
1,EDC6F1B1A69A7863,docked_bike,2021-04-27 17:28:02,2021-04-27 17:33:07,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member
2,431A76830E10408A,docked_bike,2021-04-28 18:05:19,2021-04-28 18:10:48,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member
3,C00248A0ADC009FA,docked_bike,2021-04-20 21:35:47,2021-04-20 21:56:31,Irving Ave & DeKalb Ave,4898.02,Division Ave & Hooper St,5045.05,40.702700,-73.920950,40.706842,-73.954435,casual
4,BE78810D746EE516,docked_bike,2021-04-30 00:34:54,2021-04-30 01:03:29,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280216,8A1C8DB4249BF100,classic_bike,2021-09-26 16:00:45,2021-09-26 16:20:51,8 Ave & W 31 St,6450.05,W 67 St & Broadway,7116.04,40.750585,-73.994685,40.774925,-73.982666,casual
3280217,C290EE73DF58AD79,classic_bike,2021-09-07 08:22:06,2021-09-07 08:38:40,S Portland Ave & Hanson Pl,4354.05,S 3 St & Bedford Ave,5235.05,40.685396,-73.974315,40.712605,-73.962644,casual
3280218,E42F8B93C4168658,classic_bike,2021-09-30 20:50:23,2021-09-30 20:59:13,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,casual
3280219,7221F0C58026A827,classic_bike,2021-09-08 19:06:24,2021-09-08 19:10:57,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,member
3280220,689F3FAE372C013C,classic_bike,2021-09-27 07:58:57,2021-09-27 08:02:31,West End Ave & W 60 St,7059.08,W 67 St & Broadway,7116.04,40.772370,-73.990050,40.774925,-73.982666,member

In [16]:
citibike_2021['Started At'] = pd.to_datetime(citibike_2021['Started At'])
citibike_2021['Start Date'] = citibike_2021['Started At'].dt.date
citibike_2021['Start Time'] = citibike_2021['Started At'].dt.time

In [17]:
citibike_2021

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual,Start Date,Start Time
0,7099F9531C9DA16D,docked_bike,2021-04-28 17:27:24,2021-04-28 17:34:31,DeKalb Ave & Hudson Ave,4513.06,Douglass St & 4 Ave,4175.14,40.689888,-73.981013,40.679279,-73.981540,member,2021-04-28,17:27:24
1,EDC6F1B1A69A7863,docked_bike,2021-04-27 17:28:02,2021-04-27 17:33:07,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-27,17:28:02
2,431A76830E10408A,docked_bike,2021-04-28 18:05:19,2021-04-28 18:10:48,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-28,18:05:19
3,C00248A0ADC009FA,docked_bike,2021-04-20 21:35:47,2021-04-20 21:56:31,Irving Ave & DeKalb Ave,4898.02,Division Ave & Hooper St,5045.05,40.702700,-73.920950,40.706842,-73.954435,casual,2021-04-20,21:35:47
4,BE78810D746EE516,docked_bike,2021-04-30 00:34:54,2021-04-30 01:03:29,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual,2021-04-30,00:34:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280216,8A1C8DB4249BF100,classic_bike,2021-09-26 16:00:45,2021-09-26 16:20:51,8 Ave & W 31 St,6450.05,W 67 St & Broadway,7116.04,40.750585,-73.994685,40.774925,-73.982666,casual,2021-09-26,16:00:45
3280217,C290EE73DF58AD79,classic_bike,2021-09-07 08:22:06,2021-09-07 08:38:40,S Portland Ave & Hanson Pl,4354.05,S 3 St & Bedford Ave,5235.05,40.685396,-73.974315,40.712605,-73.962644,casual,2021-09-07,08:22:06
3280218,E42F8B93C4168658,classic_bike,2021-09-30 20:50:23,2021-09-30 20:59:13,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,casual,2021-09-30,20:50:23
3280219,7221F0C58026A827,classic_bike,2021-09-08 19:06:24,2021-09-08 19:10:57,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,member,2021-09-08,19:06:24
3280220,689F3FAE372C013C,classic_bike,2021-09-27 07:58:57,2021-09-27 08:02:31,West End Ave & W 60 St,7059.08,W 67 St & Broadway,7116.04,40.772370,-73.990050,40.774925,-73.982666,member,2021-09-27,07:58:57

In [18]:
citibike_2021['Ended At'] = pd.to_datetime(citibike_2021['Ended At'])
citibike_2021['End Date'] = citibike_2021['Ended At'].dt.date
citibike_2021['End Time'] = citibike_2021['Ended At'].dt.time

In [19]:
citibike_2021

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual,Start Date,Start Time,End Date,End Time
0,7099F9531C9DA16D,docked_bike,2021-04-28 17:27:24,2021-04-28 17:34:31,DeKalb Ave & Hudson Ave,4513.06,Douglass St & 4 Ave,4175.14,40.689888,-73.981013,40.679279,-73.981540,member,2021-04-28,17:27:24,2021-04-28,17:34:31
1,EDC6F1B1A69A7863,docked_bike,2021-04-27 17:28:02,2021-04-27 17:33:07,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-27,17:28:02,2021-04-27,17:33:07
2,431A76830E10408A,docked_bike,2021-04-28 18:05:19,2021-04-28 18:10:48,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-28,18:05:19,2021-04-28,18:10:48
3,C00248A0ADC009FA,docked_bike,2021-04-20 21:35:47,2021-04-20 21:56:31,Irving Ave & DeKalb Ave,4898.02,Division Ave & Hooper St,5045.05,40.702700,-73.920950,40.706842,-73.954435,casual,2021-04-20,21:35:47,2021-04-20,21:56:31
4,BE78810D746EE516,docked_bike,2021-04-30 00:34:54,2021-04-30 01:03:29,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual,2021-04-30,00:34:54,2021-04-30,01:03:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280216,8A1C8DB4249BF100,classic_bike,2021-09-26 16:00:45,2021-09-26 16:20:51,8 Ave & W 31 St,6450.05,W 67 St & Broadway,7116.04,40.750585,-73.994685,40.774925,-73.982666,casual,2021-09-26,16:00:45,2021-09-26,16:20:51
3280217,C290EE73DF58AD79,classic_bike,2021-09-07 08:22:06,2021-09-07 08:38:40,S Portland Ave & Hanson Pl,4354.05,S 3 St & Bedford Ave,5235.05,40.685396,-73.974315,40.712605,-73.962644,casual,2021-09-07,08:22:06,2021-09-07,08:38:40
3280218,E42F8B93C4168658,classic_bike,2021-09-30 20:50:23,2021-09-30 20:59:13,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,casual,2021-09-30,20:50:23,2021-09-30,20:59:13
3280219,7221F0C58026A827,classic_bike,2021-09-08 19:06:24,2021-09-08 19:10:57,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,member,2021-09-08,19:06:24,2021-09-08,19:10:57
3280220,689F3FAE372C013C,classic_bike,2021-09-27 07:58:57,2021-09-27 08:02:31,West End Ave & W 60 St,7059.08,W 67 St & Broadway,7116.04,40.772370,-73.990050,40.774925,-73.982666,member,2021-09-27,07:58:57,2021-09-27,08:02:31

In [20]:
citibike_2021.drop(columns=['Started At', 'Ended At'])

,Ride ID,Rideable Type,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual,Start Date,Start Time,End Date,End Time
0,7099F9531C9DA16D,docked_bike,DeKalb Ave & Hudson Ave,4513.06,Douglass St & 4 Ave,4175.14,40.689888,-73.981013,40.679279,-73.981540,member,2021-04-28,17:27:24,2021-04-28,17:34:31
1,EDC6F1B1A69A7863,docked_bike,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-27,17:28:02,2021-04-27,17:33:07
2,431A76830E10408A,docked_bike,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-28,18:05:19,2021-04-28,18:10:48
3,C00248A0ADC009FA,docked_bike,Irving Ave & DeKalb Ave,4898.02,Division Ave & Hooper St,5045.05,40.702700,-73.920950,40.706842,-73.954435,casual,2021-04-20,21:35:47,2021-04-20,21:56:31
4,BE78810D746EE516,docked_bike,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual,2021-04-30,00:34:54,2021-04-30,01:03:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280216,8A1C8DB4249BF100,classic_bike,8 Ave & W 31 St,6450.05,W 67 St & Broadway,7116.04,40.750585,-73.994685,40.774925,-73.982666,casual,2021-09-26,16:00:45,2021-09-26,16:20:51
3280217,C290EE73DF58AD79,classic_bike,S Portland Ave & Hanson Pl,4354.05,S 3 St & Bedford Ave,5235.05,40.685396,-73.974315,40.712605,-73.962644,casual,2021-09-07,08:22:06,2021-09-07,08:38:40
3280218,E42F8B93C4168658,classic_bike,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,casual,2021-09-30,20:50:23,2021-09-30,20:59:13
3280219,7221F0C58026A827,classic_bike,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,member,2021-09-08,19:06:24,2021-09-08,19:10:57
3280220,689F3FAE372C013C,classic_bike,West End Ave & W 60 St,7059.08,W 67 St & Broadway,7116.04,40.772370,-73.990050,40.774925,-73.982666,member,2021-09-27,07:58:57,2021-09-27,08:02:31

In [21]:
print(pd.unique(citibike_2021['Rideable Type']))

['docked_bike' 'electric_bike' 'classic_bike']

In [24]:
citibike_2021_1 = citibike_2021.replace({'Rideable Type' : { 'docked_bike' : 'Docked Bike', 'docked_bike'  : 'Docked Bike', 'classic_bike' : 'Classic Bike' }})

In [25]:
citibike_2021_1

,Ride ID,Rideable Type,Started At,Ended At,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual,Start Date,Start Time,End Date,End Time
0,7099F9531C9DA16D,Docked Bike,2021-04-28 17:27:24,2021-04-28 17:34:31,DeKalb Ave & Hudson Ave,4513.06,Douglass St & 4 Ave,4175.14,40.689888,-73.981013,40.679279,-73.981540,member,2021-04-28,17:27:24,2021-04-28,17:34:31
1,EDC6F1B1A69A7863,Docked Bike,2021-04-27 17:28:02,2021-04-27 17:33:07,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-27,17:28:02,2021-04-27,17:33:07
2,431A76830E10408A,Docked Bike,2021-04-28 18:05:19,2021-04-28 18:10:48,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-28,18:05:19,2021-04-28,18:10:48
3,C00248A0ADC009FA,Docked Bike,2021-04-20 21:35:47,2021-04-20 21:56:31,Irving Ave & DeKalb Ave,4898.02,Division Ave & Hooper St,5045.05,40.702700,-73.920950,40.706842,-73.954435,casual,2021-04-20,21:35:47,2021-04-20,21:56:31
4,BE78810D746EE516,Docked Bike,2021-04-30 00:34:54,2021-04-30 01:03:29,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual,2021-04-30,00:34:54,2021-04-30,01:03:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280216,8A1C8DB4249BF100,Classic Bike,2021-09-26 16:00:45,2021-09-26 16:20:51,8 Ave & W 31 St,6450.05,W 67 St & Broadway,7116.04,40.750585,-73.994685,40.774925,-73.982666,casual,2021-09-26,16:00:45,2021-09-26,16:20:51
3280217,C290EE73DF58AD79,Classic Bike,2021-09-07 08:22:06,2021-09-07 08:38:40,S Portland Ave & Hanson Pl,4354.05,S 3 St & Bedford Ave,5235.05,40.685396,-73.974315,40.712605,-73.962644,casual,2021-09-07,08:22:06,2021-09-07,08:38:40
3280218,E42F8B93C4168658,Classic Bike,2021-09-30 20:50:23,2021-09-30 20:59:13,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,casual,2021-09-30,20:50:23,2021-09-30,20:59:13
3280219,7221F0C58026A827,Classic Bike,2021-09-08 19:06:24,2021-09-08 19:10:57,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,member,2021-09-08,19:06:24,2021-09-08,19:10:57
3280220,689F3FAE372C013C,Classic Bike,2021-09-27 07:58:57,2021-09-27 08:02:31,West End Ave & W 60 St,7059.08,W 67 St & Broadway,7116.04,40.772370,-73.990050,40.774925,-73.982666,member,2021-09-27,07:58:57,2021-09-27,08:02:31

In [26]:
citibike_2021_1.drop(columns=['Started At', 'Ended At'])

,Ride ID,Rideable Type,Start Station Name,Start Station Id,End Station Name,end_station_id,Start Latitude,Start Longitude,End Latitude,End Longitude,Member Casual,Start Date,Start Time,End Date,End Time
0,7099F9531C9DA16D,Docked Bike,DeKalb Ave & Hudson Ave,4513.06,Douglass St & 4 Ave,4175.14,40.689888,-73.981013,40.679279,-73.981540,member,2021-04-28,17:27:24,2021-04-28,17:34:31
1,EDC6F1B1A69A7863,Docked Bike,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-27,17:28:02,2021-04-27,17:33:07
2,431A76830E10408A,Docked Bike,E 47 St & Park Ave,6584.12,W 52 St & 6 Ave,6740.01,40.755102,-73.974986,40.761330,-73.979820,member,2021-04-28,18:05:19,2021-04-28,18:10:48
3,C00248A0ADC009FA,Docked Bike,Irving Ave & DeKalb Ave,4898.02,Division Ave & Hooper St,5045.05,40.702700,-73.920950,40.706842,-73.954435,casual,2021-04-20,21:35:47,2021-04-20,21:56:31
4,BE78810D746EE516,Docked Bike,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual,2021-04-30,00:34:54,2021-04-30,01:03:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280216,8A1C8DB4249BF100,Classic Bike,8 Ave & W 31 St,6450.05,W 67 St & Broadway,7116.04,40.750585,-73.994685,40.774925,-73.982666,casual,2021-09-26,16:00:45,2021-09-26,16:20:51
3280217,C290EE73DF58AD79,Classic Bike,S Portland Ave & Hanson Pl,4354.05,S 3 St & Bedford Ave,5235.05,40.685396,-73.974315,40.712605,-73.962644,casual,2021-09-07,08:22:06,2021-09-07,08:38:40
3280218,E42F8B93C4168658,Classic Bike,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,casual,2021-09-30,20:50:23,2021-09-30,20:59:13
3280219,7221F0C58026A827,Classic Bike,West End Ave & W 60 St,7059.08,Amsterdam Ave & W 66 St,7149.05,40.772370,-73.990050,40.774667,-73.984706,member,2021-09-08,19:06:24,2021-09-08,19:10:57
3280220,689F3FAE372C013C,Classic Bike,West End Ave & W 60 St,7059.08,W 67 St & Broadway,7116.04,40.772370,-73.990050,40.774925,-73.982666,member,2021-09-27,07:58:57,2021-09-27,08:02:31

In [28]:
citibike_2021_1.to_csv('2021-citibike-data-AprToSept.csv')